DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
    userId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(512) NOT NULL,
    money FLOAT NOT NULL DEFAULT 0.0
);